### PR TITLE
feat: [Camunda TCK Runner] Update test results 

### PR DESCRIPTION
**Pull request by saig0**
## Description 

- Update to the latest Camunda version `7.21.0`
- Publish the new test results

### CODE REVIEW

**Comment by saig0** [comment]
@baldimir here are the latest test results from Camunda. :rocket:  

cc: @falko

**Review by falko — COMMENTED** [review]
Looks good to me but I'll let @baldimir decide on the merge.

**Comment by baldimir** [comment]
Sorry for late merge, I was out sick. Merging.

**Comment by falko** [comment]
No worries. Thank you for merging.

**Pull request merged**
