### PR TITLE
test: verify non-existing function invocation

### PR DESCRIPTION
**Pull request by nikku**
Yields `null`.

----

Closes https://github.com/dmn-tck/tck/issues/539

### CODE REVIEW

**Comment by StrayAlien** [comment]
looks good to me @nikku .  Thanks.  I really thought we'd have this covered already - even accidentally - but, I don't think we do.  Good catch.  Though, just a suggestion, perhaps we could take the opportunity to examine some other simple related cases here?  

Say ...

* `null()` (returns null)
* `"somefunc"()` (returns null), where a function called `somefunc` is in scope 
* and similar to the above, invoking non functions as though they were functions.  The grammar says  function invocation is `function invocation = expression , parameters` where expression can be (well) any expression including literals.  So perhaps we could exercise a few, like `123()`, `@"2023-11-11"().  Perhaps even a double invocation like `func()()` where `func` exists in scope as a function.

Happy for comments.

**Comment by nikku** [comment]
@StrayAlien I'll add the cases you mentioned.

**Comment by StrayAlien** [comment]
Thanks @nikku .  I know they might seem a little (perhaps) silly, but, we're here to catch as many angles as we can.  Maybe a new runtime would not actually do `123()`, who knows really. Perhaps the mixup of literal vs identifier for the `"some_func"()` thingo might catch people, but, hey, I wish I has a € for every time some silly test saved my *ss. :-)  Easy to pass tests are 'free', but they're still tests ... 👍

**Comment by nikku** [comment]
@StrayAlien There is nothing better than testing different (edge) cases. So no, testing such cases does not sound silly at all.

**Pull request merged**
