### PR TITLE
Align 0083-feel-unicode to assumption made in PR #239

### PR DESCRIPTION
**Pull request by tarilabs**
that is, assumption defined in this comment:
https://github.com/dmn-tck/tck/pull/239#issuecomment-489116665

### CODE REVIEW

**Comment by tarilabs** [comment]
Based on the meeting 2019-05-10 I will actually comment out these tests.

**Comment by tarilabs** [comment]
I don't have any more reasons to propose this consistency alignment, based on the fact during TCK meeting 2019-05-11 decision was actually to comment out these tests.

@StrayAlien you may still want to take a look to what was my original proposal for tests alignments, based on https://github.com/dmn-tck/tck/pull/239#issuecomment-489116665 I am not sure if you are forking these test for your internal CI, you may want to consider my code comments. Hope possibly valuable.

I believe there will be a discussion again about these specific test cases, once https://issues.omg.org/issues/DMN13-127 is clarified.

Superseeded by https://github.com/dmn-tck/tck/pull/298 closing this PR.

**Comment by StrayAlien** [comment]
Thanks @tarilabs  - I saw your excellent ascii-art inline comments.  Thanks - I wasn't at the meeting (and I don't think the minutes have been released as yet) so don't really have much context except that maybe the string length thing is 'controversial' still! 

`((string length = cans of worms) = true)`

**Comment by tarilabs** [comment]
Correct, with #298 these 3 tests have been commented out as another vendor perspective did not agree with this PR of alignment, and was a valid/supported perspective to flag them as controversial.

**Pull request closed without merging**
