### PR TITLE
DMN 1.4 - 1151-boxed-filter

### PR DESCRIPTION
**Pull request by StrayAlien**

### CODE REVIEW

**Comment by SimonRinguette** [comment]
Test 003 should be auto-boxed since `"not a list"[true]` is valid in FEEL.

Test 006 should be auto-boxed since `1[item  >=3]` is valid in FEEL.

**Comment by baldimir** [comment]
After the discussion on the TCK meeting, let's comment the tests 003 and 006 out. When we have clarification in the RTF or changes in the spec, covering the cases, we can enable them again.

**Comment by SimonRinguette** [comment]
RTF issue: https://issues.omg.org/issues/INBOX-1770

**Comment by StrayAlien** [comment]
tests commented out as per request

**Pull request merged**
