### PR TITLE
[Camunda-DMN-Scala] Rename TCK runner

### PR DESCRIPTION
**Pull request by saig0**
* rename the TCK runner to `dmn-tck-runner-camunda-dmn-scala` as suggested [here](https://github.com/dmn-tck/tck/pull/458#issuecomment-880113690)
* rename the test results directory to `CamundaDmnScala`
* dump dependencies (#459, #460)

### CODE REVIEW

**Comment by saig0** [comment]
@tarilabs please review. Thanks!

**Review by tarilabs — COMMENTED** [review]
Thank you @saig0 , do you want to align analogous changes also in https://github.com/dmn-tck/tck/blob/master/.github/workflows/optional_dmn-scala.yml as part of this PR?

**Comment by saig0** [comment]
Good point. I'll adjust the PR :rocket:

**Comment by tarilabs** [comment]
awesome, thank you @saig0 !

**Pull request merged**
