### PR TITLE
DMN 1.5 - date increments in loops

### PR DESCRIPTION
**Pull request by StrayAlien**
Dates may now be used by loops.  Some simple tests for prove this is possible and that the increment is by a single day

### CODE REVIEW

**Comment by baldimir** [comment]
@dmn-tck/contributors please review.

**Comment by SimonRinguette** [comment]
Reviewed and test pass on the Trisotech Engine

**Comment by StrayAlien** [comment]
Thanks @SimonRinguette .  Apols, I have a few more sanity check to throw in here.  Apols. On their way.  Assertions that the other date time  type are _not_ permitted.

**Comment by StrayAlien** [comment]
Btw, as a small note here.  These tests did not have any actual ranges as iterations contexts.  I have added some as the spec does refer to 'ranges' of numbers and dates, but, I have a feeling the absence of actual ranges in these tests was the result of some early discussion whereby it was agreed that the spec did not permit 'range' types here.  At any rate, the tests now have actual range values.

**Comment by opatrascoiu** [comment]
Looks good to me.

**Pull request merged**
