### PR TITLE
Update from DMN 1.3 to DMN 1.4

### PR DESCRIPTION
**Pull request by falko**

### CODE REVIEW

**Comment by baldimir** [comment]
@dmn-tck/contributors please review, DMN 1.4 is officially out, so if there are no objections, we need to merge this.

**Comment by StrayAlien** [comment]
hey @baldimir , @opatrascoiu - shall we just tag what we have now and merge this in?  Any outstanding PRs can be updated.  It seems sensible to merge and then we can keep moving.

Though, I do have to ask, why do we need to update all the tests every version change?  What is wrong with just leaving them as they are?  The expectations of runtimes being to run them at the current TCK supported DMN level - despite the namespace.   If a new DMN version has in breaking changes then maybe we update the tests / namespaces appropriately.

**Comment by StrayAlien** [comment]
bump

**Comment by baldimir** [comment]
Sorry for late reply, I will take a look this week.

**Comment by StrayAlien** [comment]
Thanks @baldimir - I've got a first pass done on (what I think are) all new aspects of 1.4.  (Except for negative scales)

**Comment by opatrascoiu** [comment]
I think we should merge the following PRs before this:

https://github.com/dmn-tck/tck/pull/366
https://github.com/dmn-tck/tck/pull/422
https://github.com/dmn-tck/tck/pull/540

AFAIK they are ready to go in.

I would also merge the tests for allowed values first as well.

**Comment by StrayAlien** [comment]
@opatrascoiu - just investigating your comment on #422. So, no merge on that one as yet please.

**Comment by baldimir** [comment]
I have merged what was reviewed and possible to merge. So I am waiting with https://github.com/dmn-tck/tck/pull/422.

**Comment by StrayAlien** [comment]
@baldimir - can we leave #422 for now and just merged this?  @opatrascoiu - agree?

**Comment by baldimir** [comment]
@StrayAlien I am ok with that.

**Comment by opatrascoiu** [comment]
@baldimir @StrayAlien I am ok with leaving the allowed values PR behind. We need to check if after merging this there are no DMN 1.3 files in the master branch.

**Comment by baldimir** [comment]
I am trying to rebase this with latest changes. Will update the PR when ready.

**Comment by baldimir** [comment]
I couldn't force push dmn1.4 branch after rebase, so I created a new PR. Please doublecheck that one https://github.com/dmn-tck/tck/pull/613. When fine, this one will be closed.

**Comment by baldimir** [comment]
The new PR is merged, closing this one.

**Pull request closed without merging**
