### PR TITLE
0079-feel-string-function

### PR DESCRIPTION
**Pull request by StrayAlien**

### CODE REVIEW

**Comment by tarilabs** [comment]
Based on the explaination provided in TCK meeting about standardization and consensus concerning `string` FEEL function, I would vote to hold this test case or move in non-conformant folder

**Comment by agilepro** [comment]
We would like to move string tests in the "non-conformant" folder where vendors can run the test, but the results are not reported on the web site.   @StrayAlien Can you move this?

**Comment by StrayAlien** [comment]
@agilepro, @tarilabs. moved.

**Comment by tarilabs** [comment]
thanks for the move, lgtm

**Pull request merged**
