### PR TITLE
Update Drools to 8.40.0.Final

### PR DESCRIPTION
**Pull request by baldimir**

### CODE REVIEW

**Review by tarilabs — APPROVED** [review]
looks good to me?

**Comment by opatrascoiu** [comment]
The XML validation fails - we should fix it.

**Comment by opatrascoiu** [comment]
@tarilabs I agree. I'll raise a PR to fix it.

**Comment by baldimir** [comment]
@tarilabs I created new issue for those tests that started to fail. I need to investigate. Will merge this as it is now. https://github.com/kiegroup/kie-issues/issues/357

**Pull request merged**
