### PR TITLE
0074-feel-properties

### PR DESCRIPTION
**Pull request by StrayAlien**

### CODE REVIEW

**Comment by tarilabs** [comment]
rechecked and good for me, thanks!

**Comment by tarilabs** [comment]
[headsup for merge, please use commit message `0074-feel-properties`]

**Comment by opatrascoiu** [comment]
`Table 62: List of properties per type`  contains for each temporal type a list of allowed properties.

There are tests for the incorrect use of these properties. The expected value is null, which correct. 
However, because this is a semantic error, the errorResult must be true. For example, ym_duration_003.

**Comment by StrayAlien** [comment]
thanks @opatrascoiu.  I have to admit to being a little vague of what the idea of an 'error' is in the test suite granted the spec says nothing about error conditions beyond for functions returning null.  I'm am opening an issue to clarify.

**Pull request merged**
