### PR TITLE
Propose TCK Validation extension to check for DMN namespace uniqueness

### PR DESCRIPTION
**Pull request by tarilabs**
within each given TCK test case folder(s).

### CODE REVIEW

**Comment by tarilabs** [comment]
Demonstration using 193cf93

image

in job log tail:
image

in job log is reported the full exception message:
image

```
testDMNFilesUniqueInNamespace[TestCase 0001-filter](org.omg.dmn.tck.validation.TestCasesFiles)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.RuntimeException: There are 2 or more files with the same DMN namespace: http://www.trisotech.com/definitions/_f52ca843-504b-4c3b-a6bc-4d377bffef7a
in the folder: ../../TestCases/compliance-level-3/0001-filter
these files are: [../../TestCases/compliance-level-3/0001-filter/0001-filter.dmn, ../../TestCases/compliance-level-3/0001-filter/0001-filter2.dmn]
```

**Comment by tarilabs** [comment]
If there is consensus about namespace uniqueness between models which are related by an import relationship as per https://github.com/dmn-tck/tck/pull/272#issuecomment-489470820 then this TCK Validation test case folder check:

ensures within a given TCK test case folder, the `*.dmn` models file have a unique namespace --within that TCK test case folder.

**Comment by StrayAlien** [comment]
Thanks @tarilabs - seems fair enough given the recent discussions.

**Comment by agilepro** [comment]
discussed on May 24.   Agreed that this is OK to go.   Just waiting for the end of the month.

**Pull request merged**
