### PR TITLE
[DMN 1.5] Add tests for equality operators in positive unary tests to the TCK suite

### PR DESCRIPTION
**Pull request by kbowers-ibm**
Adding tests for positive unary tests.

### CODE REVIEW

**Comment by baldimir** [comment]
Thanks Kennedy. If the group agree to merge this, it needs to be done after the current master is branched for DMN 1.4.

**Comment by baldimir** [comment]
@dmn-tck/contributors please review

**Comment by SimonRinguette** [comment]
Tested on the Trisotech engine and it works. 

Not sure why this would go to `dmn-tck:dmn1.5` instead of master. because its DMN 1.3

**Comment by opatrascoiu** [comment]
I think is because support for the operators = and != in simple positive unary test (before endpoints) was added in DMN 1.5 https://issues.omg.org/browse/DMN15-108

**Comment by SimonRinguette** [comment]
Make sense

**Comment by dsntk** [comment]
There are already tests for **1131** in main. Test case directory and file names have to be adjusted. Otherwise existing tests will be overridden.

**Comment by baldimir** [comment]
I will fix it. Thanks for noticing this.

**Comment by opatrascoiu** [comment]
The tests look good to me apart from the filename (1131 is already taken by another test case)

**Comment by StrayAlien** [comment]
I think these cases are already covered in "0072 feel in tests".

**Comment by opatrascoiu** [comment]
@StrayAlien The == and != are not covered as they were introduced in DMN 1.5. How about we add tests for == and != in 0072 to keep all trhe in tests in one place?

**Comment by StrayAlien** [comment]
Thanks @opatrascoiu .  That what this current PR is for: https://github.com/dmn-tck/tck/pull/668.   It asserts on those operators for FEEL types - except list because this is still uncertain I think.  (as well as uncommenting some null tests we had in there to see if they now are valid)

**Comment by opatrascoiu** [comment]
I checked the tests in PR #668 and they cover the ones here.

@kbowers-ibm @baldimir I think it makes sense to close this MR and focus the review on the one mentioned by @StrayAlien as it groups the test cases for unary tests in an already existing test file.

**Pull request closed without merging**
