### PR TITLE
update to Java 11 version

### PR DESCRIPTION
**Pull request by gautric**
- updating github action
- updating pom.xml

### CODE REVIEW

**Comment by tarilabs** [comment]
I believe the TCK worked already with JDK11+.
(IIRC I've always checked with 1.8, 11 and 17).

This PR would bump min Java requirement to 11, but not sure why?

**Comment by baldimir** [comment]
I personally agree with bumping the default to 11 as Java 8 very old now.

**Review by tarilabs — COMMENTED** [review]
https://github.com/dmn-tck/tck/pull/511#issuecomment-1268295797 was provided.

**Comment by baldimir** [comment]
Also this PR is not just about raising the minimal Java version, but actually running the PR checks on Java 11. That is a good thing in my opinion.

**Review by baldimir — APPROVED** [review]

**Comment by baldimir** [comment]
Hi @gautric, thank you for the contribution. I am sorry for the delays. Could you please rebase your PR?

**Comment by baldimir** [comment]
We discussed this on a TCK meeting and there are no objections to this. I will ping contributors to find out last time if anyone has objections. If not and it is rebased, I will merge this.

**Comment by baldimir** [comment]
One question on the meeting about this was that for the marshaller module, there would need to be dependencies checked, but there is already a profile in the pom.xml for java 9+ that gets automatically enabled, that adds required dependencies. So this is not a problem.

**Pull request closed without merging**
