### PR TITLE
Update from DMN 1.3 to DMN 1.4 - latest rebase

### PR DESCRIPTION
**Pull request by baldimir**
This is a rebase of https://github.com/dmn-tck/tck/pull/546 with the latest changes from master. I don't have permissions to force push to dmn1.4 branch, so doing it this way. 

@dmn-tck/contributors please review. You can see the changes that are new in the commits list.

### CODE REVIEW

**Comment by baldimir** [comment]
@tarilabs could you please do a 1.3 tag? I think I don't have rights to do that.

**Comment by tarilabs** [comment]
> @tarilabs could you please do a 1.3 tag? I think I don't have rights to do that. It needs to be done before this gets merged.

not sure why, as you have all the permissions from panel; if you do `git push upstream <tag_name>` referencing a commit on the default branch, what do you get?

if that does fail, which commit you want me to tag? latest commit on the default branch?

**Comment by baldimir** [comment]
Ok, thanks, it worked.

**Comment by opatrascoiu** [comment]
Looks good to me.

**Pull request merged**
