### PR TITLE
DMN 1.4 - 1142-feel-round-down-function

### PR DESCRIPTION
**Pull request by StrayAlien**

### CODE REVIEW

**Comment by opatrascoiu** [comment]
The issue with the  "Scale is in the range [−6111 ..6176]" has been clarified in RTF. The tests look good to me.

**Comment by SimonRinguette** [comment]
RTF issue: https://issues.omg.org/issues/INBOX-1769

**Comment by StrayAlien** [comment]
commented out test 6 as per request

**Comment by SimonRinguette** [comment]
The 11b test that call using a named parameter (only one) should have also been removed with test 6 because it is the same test but with named parameter

**Comment by StrayAlien** [comment]
11b commented out

**Pull request merged**
