### PR TITLE
chore(runner/camunda): update Camunda runner and test results

### PR DESCRIPTION
**Pull request by saig0**

### CODE REVIEW

**Comment by tarilabs** [comment]
@saig0 thank you for this PR.

As Jenkins notes: https://travis-ci.org/dmn-tck/tck/jobs/454361046#L1599
This PR would introduce 2 versions for the same Vendor, and we actually invite Vendor to submit only for 1 version per implementation.

In other words, I can see this PR is 

- adding a new result file inside: `TestResults/Camunda/7.9.0/tck_results.csv`

but 

- for `7.9.0` is missing the companion `.properties` file (you can copy and amend from previous version)
- not removing (superseeded) `TestResults/Camunda/7.8.0` directory

Can you kindly amend this PR to reflect necessary changes, please?
I believe with these changes Jenkins would validate the PR as green.
Thanks!
/cc @falko

**Comment by tarilabs** [comment]
Looks good to me now, thanks @falko for the updates

**Comment by falko** [comment]
Thank you for the GitHub hint. We will still try to get that last remaining test fixed until next week.

**Comment by falko** [comment]
@tarilabs we will fix the remaining three tests with DMN 1.2. Could you please publish the DMN 1.1 results one last time as discussed in last weeks meeting?

**Comment by tarilabs** [comment]
> we will fix the remaining three tests with DMN 1.2. 

understood, thanks for the headsup

>  Could you please publish the DMN 1.1 results one last time as discussed in last weeks meeting?

at this point I will publish at the end of month as per usual past schedule deadlines, hopefully at the next meeting we are also going to discuss about DMNv1.2 merge as well ;)

/cc @agilepro @etirelli

**Pull request merged**
