### PR TITLE
DO NOT MERGE: Issue-35 : moving test CL3/0031 to non-compliant until it is refactored

### PR DESCRIPTION
**Pull request by etirelli**
Since today is the deadline for test case inclusion in the August report, we should move the test case to non-compliant folder, as per the discussion in Issue #35, until we have time to discuss it. We can refactor it and move it back to include it in the test cases for September.

### CODE REVIEW

**Comment by arthware** [comment]
I wasn't sure on that either. Of course we can refactor the test, to remove this ambiguity. 
I'll create another pull request to fix this.

**Comment by arthware** [comment]
I fixed the type ambiguity in PR #38. 
 
Therefore I suggest to merge PR #38 first (which fixes the root cause) and decide afterwards if the test case still should be moved to non-compliant temporarily (e.g. merge this PR).

**Comment by etirelli** [comment]
I will close this PR in favour of #38 when I merge that.

**Pull request closed without merging**
