### PR TITLE
non-compliant: 0019-flight-rebooking

### PR DESCRIPTION
**Pull request by StrayAlien**
small update here to remove 'feel:' from typeRefs.  One typeref changed from string to number.  `Passenger1.Miles` is represented elsewhere in the model as a number.

```xml
		        <input id="b_Passenger_Priority_dt_i_P1_Miles" label="Passenger1.Miles">
		            <inputExpression typeRef="number">
		                <text>Passenger1.Miles</text>
		            </inputExpression>
		        </input>
```

### CODE REVIEW

**Comment by agilepro** [comment]
Matteo asks the question: why is this in the non-compliant folder?   He also want to check to see if all the changes have been made to make this 1.2 compliant.

**Comment by tarilabs** [comment]
@StrayAlien could you also double-check for the whitespace changes which looks have been commited in, please?

**Comment by tarilabs** [comment]
could it be the line-ending?

**Comment by StrayAlien** [comment]
re line endings - strange - my local diff shows just my changes. I'll check it out. Thanks.

Re why this is in non-compliant?  Recursion I believe.

My personal feeling is that is should be non-compliant still because BKM recursion is a grey area of the spec.  Despite the fact that I want it there and that I like it, I would say that it is not actually supported by the spec.  This is also why my recent PR on recursion tests is in the non-compliant folder.

(btw, this is unlike self-referencing ItemDefinitions which I do think is supported by the spec) 

But I think we should get recursion in the spec!.  :-)

I'll open an issue with the OMG and create issue here so we can track it.

**Comment by StrayAlien** [comment]
Re line endings - sorry, I'm not sure what is going on there.  I checked out the previous version of the file and pushed it so as to revery the changes and git still thought I had made changes in some way.  I'm on windows with git autocrlf set to true - as it has been for all other commits.

The reverted file seems to have crlf on all line endings as you would expect.  I have reapplied all my changes to the revert files and no joy.

So, apologies for the 'noise' but the changes are really just removing 'feel:' and 'kie:' from types and the change mentioned above to change from string to number:

```xml
<input id="b_Passenger_Priority_dt_i_P1_Miles" label="Passenger1.Miles">
    <inputExpression typeRef="number">
        <text>Passenger1.Miles</text>
    </inputExpression>
</input>
```    

Apols again ...

**Comment by StrayAlien** [comment]
anything wrong with this PR?

**Comment by tarilabs** [comment]
> anything wrong with this PR?

as mentioned in previous comments, the original commits introduced "whitespace" changes for the whole file which impacted for the full file change, and personally I would avoid unless strictly necessary. 

I appended some commits which should perform as you proposals, but without this issue. When the PR will be squash+merged, as this was raised by you, the resulting commit on master will attribute to you.

**Comment by StrayAlien** [comment]
Thanks @tarilabs - I coudn't get to the bottom of that!  All indications here were just those lines were changed.  Even looking in a hex editor.  I can only suspect something weirdo about CR/LF conversions somewhere.

Thanks again, and once more, apologies for the hassle.  Not intended.

**Pull request merged**
